module.exports = {
	SAVE_MEMBER: 'SAVE_MEMBER',
	RECEIVE_MEMBERS: 'RECEIVE_MEMBERS',
	REMOVE_MEMBER: 'REMOVE_MEMBER',
	EDIT_MEMBER: 'EDIT_MEMBER',
	UPDATE_MEMBER: 'UPDATE_MEMBER',
	CANCEL_EDIT: 'CANCEL_EDIT'
}
